name: Deploy deuxpots app
on:
  push:
    branches:
      - main

jobs:

  build:
    name: Build frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 20.1.0
        uses: actions/setup-node@v3
        with:
          node-version: 20.1.0
      - run: npm install
        working-directory: ./frontend
      - run: npm run build
        working-directory: ./frontend
      - uses: actions/upload-artifact@master
        with:
          name: build
          path: frontend/build

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@master
        with:
          name: build
          path: frontend/build
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        working-directory: ./
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
